name: Build Redmi AX6000 Firmware

on:
  workflow_dispatch:

env:
  REPO_BRANCH: master
  CONFIG_FILE: ax6000.config
  DIY_P2_SH: diy-part2.sh
  UPLOAD_FIRMWARE: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo apt update -y
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Update & Install Feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration & DIY Script
      run: |
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE .config
        chmod +x $DIY_P2_SH
        ./$DIY_P2_SH
        make defconfig

    - name: Download DL Package
      run: |
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile Firmware
      id: compile
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Organize Files
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload Firmware to Artifact
      uses: actions/upload-artifact@v4
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_Redmi_AX6000_Firmware
        path: ${{ env.FIRMWARE_PATH }}
